name: Trigger production deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Run trigger
        run: |
          curl -X POST \
          -H 'Accept: application/vnd.github.v3+json' \
          https://api.github.com/repos/climatesubak/docker-ckan/dispatches \
          -u subakci:${{ secrets.GH_PAT }} \
          -d '{"event_type": "trigger-prod-deploy", "client_payload": {}}'